-- MySQL Script generated by MySQL Workbench
-- Tue Oct 26 11:39:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco_teste
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco_teste
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco_teste` DEFAULT CHARACTER SET utf8 ;
USE `banco_teste` ;

-- -----------------------------------------------------
-- Table `banco_teste`.`Temas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_teste`.`Temas` (
  `id_Temas` BIGINT(20) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_Temas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_teste`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_teste`.`Usuarios` (
  `id_Usuarios` BIGINT(20) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_Usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_teste`.`Postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_teste`.`Postagem` (
  `id_Postagem` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `texto` VARCHAR(1000) NOT NULL,
  `data` DATE NOT NULL,
  `id_Temas` BIGINT(20) NOT NULL,
  `id_Usuarios` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id_Postagem`),
  INDEX `fk_Postagem_Temas_idx` (`id_Temas` ASC) VISIBLE,
  INDEX `fk_Postagem_Usuarios1_idx` (`id_Usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Postagem_Temas`
    FOREIGN KEY (`id_Temas`)
    REFERENCES `banco_teste`.`Temas` (`id_Temas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Postagem_Usuarios1`
    FOREIGN KEY (`id_Usuarios`)
    REFERENCES `banco_teste`.`Usuarios` (`id_Usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
